---
language: ruby
sudo: false
cache: bundler
bundler_args: --without dev
script: "bundle exec rake ci"
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - ruby-head
  - jruby-9000
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9000
    - rvm: jruby-head
    - rvm: rbx-2
  fast_finish: true
notifications:
  email: false
